### PR TITLE
Update location of images for icons while decoding saved Bongo buffers

### PR DESCRIPTION
**Pull request by iqbalansari**
Fix for #34  

**EDIT** - I have also added a commit to restore foreground and background for the images

### CODE REVIEW

**Comment by iqbalansari** [comment]
Hi @dbrock, 

Just a gentle reminder, you got a chance to look into this?

Thanks

**Comment by iqbalansari** [comment]
Hi @dbrock, 

Just a gentle reminder, you got a chance to look into this?

Thanks

**Comment by dbrock** [comment]
Haha, thanks man. You are crazy! 😹

**Comment by iqbalansari** [comment]
You are welcome :smile:

**Pull request merged**
